title: Ruby on Rails - Wikipedia's Entry
copyright: Copyright (c) 2008 Wikipedia, All Rights Reserved
authors:
  - Wikipedia
subject: Ruby on Rails
keywords: rails, ruby, framework, development
theme: eiffel
base_url: http://example.com