title: [Your Book Title]
copyright: Copyright (c) <%= Time.now.year %> [Your Name], All Rights Reserved
authors:
  - [Your Name]
  - [Other Name]
subject: [Write down what your book is about]
keywords: [The keywords related to your book]
theme: <%= theme %>