title: "[Your Book Title]"
year: 2009
authors:
  - "[Your Name]"
subject: "[Your book description]"
keywords: "[Your book keywords (comma-separated)]"
theme: idle
base_url: http://example.com
copyright: "[Your copyright info]"